Script started on Fri Sep 15 22:39:09 2023
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hgit rev-parse --abbrev-ref HEAD[27D--branch[2C                 [18D[9Dbranche  push   [8Dscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 22:39:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 22:39:46] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 22:39:46] "[36mGET /static/favicon.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 22:39:47] "[36mGET /static/tablesort.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 22:39:47] "[36mGET /static/MaterialIconFont.woff2 HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 22:39:48] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 22:39:48] "GET /images/android-desktop.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 22:40:37] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% for nameForOptionalField, dataForOptionalField in userData['optional'].items() %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'optional'
127.0.0.1 - - [15/Sep/2023 22:40:37] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 22:40:37] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 22:40:37] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/user.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
^C
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 23:30:28] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% for nameForOptionalField, dataForOptionalField in userData['optional'].items() %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'optional'
127.0.0.1 - - [15/Sep/2023 23:30:29] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:30:29] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:30:29] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:30:29] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/models.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 23:34:21] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.optionalData

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 41, in initializeRequest
    g.current_user = user.get_user(session['acc_id'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/user.py", line 49, in get_user
    return m.User.query.get(userid)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1131, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1140, in _get_impl
    return self.session._get_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3700, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.optionalData
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.fullname AS user_fullname, user.email AS user_email, user.password AS user_password, user."passwordToken" AS "user_passwordToken", user."passwordResetTimer" AS "user_passwordResetTimer", user."highPermissionLevel" AS "user_highPermissionLevel", user."isOffice" AS "user_isOffice", user."userData" AS "user_userData", user."optionalData" AS "user_optionalData" 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
127.0.0.1 - - [15/Sep/2023 23:34:21] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:21] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:21] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:22] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
^C
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 23:34:40] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.optionalData

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 41, in initializeRequest
    g.current_user = user.get_user(session['acc_id'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/user.py", line 49, in get_user
    return m.User.query.get(userid)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1131, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1140, in _get_impl
    return self.session._get_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3700, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.optionalData
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.fullname AS user_fullname, user.email AS user_email, user.password AS user_password, user."passwordToken" AS "user_passwordToken", user."passwordResetTimer" AS "user_passwordResetTimer", user."highPermissionLevel" AS "user_highPermissionLevel", user."isOffice" AS "user_isOffice", user."userData" AS "user_userData", user."optionalData" AS "user_optionalData" 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
127.0.0.1 - - [15/Sep/2023 23:34:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:49] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.optionalData

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 41, in initializeRequest
    g.current_user = user.get_user(session['acc_id'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/user.py", line 49, in get_user
    return m.User.query.get(userid)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1131, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 1140, in _get_impl
    return self.session._get_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3700, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.optionalData
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.fullname AS user_fullname, user.email AS user_email, user.password AS user_password, user."passwordToken" AS "user_passwordToken", user."passwordResetTimer" AS "user_passwordResetTimer", user."highPermissionLevel" AS "user_highPermissionLevel", user."isOffice" AS "user_isOffice", user."userData" AS "user_userData", user."optionalData" AS "user_optionalData" 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
127.0.0.1 - - [15/Sep/2023 23:34:49] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:49] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:49] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:34:50] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hfflask db migrate[?2004l
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added column 'user.optionalData'
  Generating /Users/I569113/Documents/SWE/HWR23-SWEng/migrations/versions/72e70a3617f0_.py ...  done
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hfflask db update[?2004l
Usage: flask db [OPTIONS] COMMAND [ARGS]...
Try 'flask db --help' for help.

Error: No such command 'update'.
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hflask db update    grade[?2004l
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade fc2279507147 -> 72e70a3617f0, empty message
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hflask db upgradedate migrate[?2004l
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hflask db migrateup[3Cd[1C[?2004l
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hflask db upgrademi[3Ct[1C[?2004l
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.env] No changes in schema detected.
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hflask db migrateup[3Cd[1Cmi[3Ct[1Cup[3Cd[1Cdate migrate[16Dscripts/run     [?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 23:36:00] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% for nameForOptionalField, dataForOptionalField in optionalData.items() %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'optionalData' is undefined
127.0.0.1 - - [15/Sep/2023 23:36:00] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:36:00] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:36:00] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:36:01] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 23:40:35] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% for nameForOptionalField, dataForOptionalField in optionalData.items() %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'optionalData' is undefined
127.0.0.1 - - [15/Sep/2023 23:40:35] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:40:35] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:40:35] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:40:35] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/user.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 23:43:23] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% for nameForOptionalField, dataForOptionalField in optionalData.items() %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'optionalData' is undefined
127.0.0.1 - - [15/Sep/2023 23:43:23] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:43:23] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:43:24] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:43:24] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:43:27] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% for nameForOptionalField, dataForOptionalField in optionalData.items() %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'optionalData' is undefined
127.0.0.1 - - [15/Sep/2023 23:43:27] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:43:27] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:43:27] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:43:27] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
^C
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [15/Sep/2023 23:45:28] "GET /account-settings HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 23:45:29] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:29] "[36mGET /static/favicon.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:29] "[36mGET /static/tablesort.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:29] "[36mGET /static/MaterialIconFont.woff2 HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:30] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 23:45:30] "GET /images/android-desktop.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 23:45:34] "GET /account-settings HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 23:45:34] "[36mGET /static/tablesort.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:34] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:35] "[36mGET /static/favicon.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:35] "[36mGET /static/MaterialIconFont.woff2 HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Sep/2023 23:45:35] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2023 23:45:35] "GET /images/android-desktop.png HTTP/1.1" 200 -
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:08:09] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% if current_user.optionalData.length() > 0 %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'length'
127.0.0.1 - - [16/Sep/2023 00:08:09] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:08:09] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:08:09] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:08:10] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:08:50] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% if current_user.userData.length() > 0 %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'length'
127.0.0.1 - - [16/Sep/2023 00:08:50] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:08:50] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:08:50] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:08:51] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:09:40] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% if len(current_user.optionalData) > 0 %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'len' is undefined
127.0.0.1 - - [16/Sep/2023 00:09:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:09:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:09:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:09:40] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:17:26] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:17:26] "GET /images/android-desktop.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:17:28] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:17:29] "GET /images/android-desktop.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:17:30] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:17:30] "GET /images/android-desktop.png HTTP/1.1" 200 -
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:17:44] "[35m[1mGET /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 273, in changeSettings
    return render_template('account-settings.html', userData = user.get_user_data(g.current_user.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 1, in top-level template code
    {% set title = lang["account-settings"]%} {% extends "master.html" %} {% block body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/master.html", line 79, in top-level template code
    {% block body %} {% endblock body %}
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/templates/account-settings.html", line 94, in block 'body'
    {% for nameForOptionalField, dataForOptionalField in optionalData.items() %}
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'optionalData' is undefined
127.0.0.1 - - [16/Sep/2023 00:17:45] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:17:45] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:17:45] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:29:16] "GET /account-settings HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:29:16] "[36mGET /static/favicon.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:29:16] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:29:16] "[36mGET /static/tablesort.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:29:17] "[36mGET /static/MaterialIconFont.woff2 HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:29:17] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:29:17] "GET /images/android-desktop.png HTTP/1.1" 200 -
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:30:29] "GET /account-settings HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:30:29] "[36mGET /static/styles.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:30:29] "[36mGET /static/tablesort.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:30:29] "[36mGET /static/favicon.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:30:29] "[36mGET /static/MaterialIconFont.woff2 HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:30:30] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:30:30] "GET /images/android-desktop.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:30:42] "[35m[1mPOST /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 269, in changeSettings
    user.modify_user_password(g.current_user.id, user.hashPassword(request.form["passwordValidation"]))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 192, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'passwordValidation'
127.0.0.1 - - [16/Sep/2023 00:30:42] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:30:42] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:30:42] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:30:43] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:32:45] "[35m[1mPOST /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 269, in changeSettings
    user.modify_user_password(g.current_user.id, user.hashPassword(request.form["setNewPassword"]))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 192, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'setNewPassword'
127.0.0.1 - - [16/Sep/2023 00:32:45] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:32:45] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:32:45] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:32:46] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
^C[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004h[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                                                                                            [0m[27m[24m[JI569113@C02WK21CHV2R HWR23-SWEng % [K[?2004hscripts/run[?2004l
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-745-167
127.0.0.1 - - [16/Sep/2023 00:33:22] "[35m[1mPOST /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 269, in changeSettings
    user.modify_user_password(g.current_user.id, user.hashPassword(request.form["passwordValidation"]))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 192, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'passwordValidation'
127.0.0.1 - - [16/Sep/2023 00:33:22] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:33:22] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:33:22] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:33:22] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:33:25] "[35m[1mPOST /account-settings HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 269, in changeSettings
    user.modify_user_password(g.current_user.id, user.hashPassword(request.form["passwordValidation"]))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 192, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'passwordValidation'
127.0.0.1 - - [16/Sep/2023 00:33:25] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:33:25] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:33:25] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:33:25] "[36mGET /account-settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:36:58] "GET /images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:36:58] "GET /images/android-desktop.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2023 00:37:03] "[35m[1mPOST /account-settings-data HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/I569113/Documents/SWE/HWR23-SWEng/simpleticket.py", line 281, in updateUserData
    myForm = request.form["newDataSubmitionForm"].to_dict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 192, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'newDataSubmitionForm'
127.0.0.1 - - [16/Sep/2023 00:37:03] "[36mGET /account-settings-data?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:37:03] "[36mGET /account-settings-data?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:37:03] "[36mGET /account-settings-data?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2023 00:37:03] "[36mGET /account-settings-data?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
